-- DDL = CONJUNTO DE INSTRUÇÕES PARA CRIAR A ESTRUTURA DO BANCO DE DADOS, COM,O FOI BEM DEFINIDO EM AULA: PARA CRIAR A CASCA SE NENUM DADO

-- OS COMANDOS CREATE, ALTER E DROP SÃO PARA CRIAR COLUNAS, ATRIBUTOS, PROCEDURES, TRIGGERS...

-- AS INSTRUÇÕES MAIS UTILIZADAS SÃO:
-- LEMBRANDO QUE SÃO PALAVRAS RESERVADAS.

-- CREATE DATABASE (PARA CRIAR O BANCO)
-- CREATE TABLE (PARA CRIAR TABELAS)
-- ALTER TABLE (PARA ALTERAR TABELAS)
-- DROP TABLE (PARA DELETAR TABELAS E BANCOS)

-- OS COMANDOS VARIAM DE BANCOS, E É PRECISO REALIZAR CONSULTAS NAS DOCUMENTAÇÕES PARA NÃO TER ERROS/PERÍGOS


-- CASO PRECISE INSERIR NOVA COLUNA, O COMANDO É: 
-- ALTER TABLE BIBIOTECA ADD COLUMN NOME_COLUNA VARCHAR(150);


-- PARA CRIAR O BANCO:
CREATE DATABASE BIBLIOTECA;

-- PARA CONTINUAR E CONSEGUIRMOS CRIAR AS TABELAS, PRECISAMOS COLOCAR O BANCO EM ATIVIDADE (EM USO): 
USE BIBLIOTECA;

CREATE TABLE ASSOCIADOS(
	ID_ASSOCIADOS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(150) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL
);

CREATE TABLE TELEFONE(
	ID_TELEFONE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TELEFONE VARCHAR(100),
    COD_ID_ASSOCIADO INT
);

CREATE TABLE LIVRO(
	ID_LIVRO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    ANO_CRIACAO DATE NOT NULL,
    ANO_PUCLICACAO DATE NOT NULL,
    COD_ID_AUTOR INT NOT NULL,
	COD_ID_EDITORA INT NOT NULL
);

CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (50) NOT NULL,
    SOBRENOME VARCHAR(150) NOT NULL
);

CREATE TABLE EDITORA(
	ID_EDITORA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(150) NOT NULL,
    NOME_FANTASIA VARCHAR(150) NOT NULL
);

CREATE TABLE EMPRESTIMO(
	ID_EMPRESTIMO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATA_EMPRESTIMO DATE NOT NULL,
    PRAZO_DEVOLUCAO DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    ID_COD_ASSOCIADOS INT NOT NULL
);

CREATE TABLE EMPRESTIMO_EXEMPLAR(
	ID_EMPRESTIMO_EXEMPLAR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    COD_ID_EMPRESTIMO INT NOT NULL,
    COD_ID_EXEMPLAR INT NOT NULL
);

CREATE TABLE EXEMPLAR(
	ID_EXEMPLAR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SINISTRO BOOLEAN
);


-- INSERINDO COLUNA NA TABELA EXEMPLAR

ALTER TABLE EXEMPLAR ADD COLUMN COD_ID_LIVRO INT;


-- ALTERANDO COLUNA DA TABELA LIVRO:
ALTER TABLE LIVRO CHANGE ANO_PUCLICACAO ANO_PUBLICACAO DATE;


-- CRIANDO CONSTRAINTS (CHAVES ESTRANGEIRAS - VULGO FOREIGN KEY)

-- ALTER TABLE `TELEFONE` ADD CONSTRAINT `FK_TELEFONE_ASSOCIADOS` FOREIGN KEY ( `COD_ID_ASSOCIADO` ) REFERENCES `ASSOCIADOS` ( `ID_ASSOCIADOS` ) ;
-- ALTER TABLE `LIVRO` ADD CONSTRAINT `FK_LIVRO_AUTOR` FOREIGN KEY ( `COD_ID_AUTOR` ) REFERENCES `AUTOR` ( `ID_AUTOR`) ;
-- ALTER TABLE `LIVRO` ADD CONSTRAINT `FK_LIVRO_EDITORA` FOREIGN KEY ( `COD_ID_EDITORA` ) REFERENCES `EDITORA` ( `ID_EDITORA`) ;
-- ALTER TABLE `EMPRESTIMO` ADD CONSTRAINT `FK_EMPRESTIMO_ASSOCIADOS` FOREIGN KEY ( `ID_COD_ASSOCIADOS` ) REFERENCES `ASSOCIADOS` ( `ID_ASSOCIADOS` ) ;
-- ALTER TABLE `EMPRESTIMO_EXEMPLAR` ADD CONSTRAINT `FK_EMPRESTIMO_EXEMPLAR_EMPRESTIMO` FOREIGN KEY ( `COD_ID_EMPRESTIMO` ) REFERENCES `EMPRESTIMO` ( `ID_EMPRESTIMO` ) ;
-- ALTER TABLE `EMPRESTIMO_EXEMPLAR` ADD CONSTRAINT `FK_EMPRESTIMO_EXEMPLAR_EXEMPLAR` FOREIGN KEY ( `COD_ID_EXEMPLAR` ) REFERENCES `EXEMPLAR` ( `ID_EXEMPLAR` ) ;
-- ALTER TABLE `EXEMPLAR` ADD CONSTRAINT `FK_EXEMPALR_LIVRO` FOREIGN KEY ( `COD_ID_EMPRESTIMO` ) REFERENCES `EMPRESTIMO` ( `ID_EMPRESTIMO` ) ;
-- ALTER TABLE `EXEMPLAR` ADD CONSTRAINT `FK_EXEMPLAR_LIVRO` FOREIGN KEY (`COD_ID_LIVRO`) REFERENCES `LIVRO` (`ID_LIVRO`);