-- CONJUNTO DE INTRUÇOES DML
-- MANIPULAÇÃO DE DADOS DAS TABELAS


-- INSERINDO DADOS NA TABELA ASSOCIADOS OS INTEGRANTES DO GRUPO:

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("GABRIEL", "AZEVEDO OLIVEIRA SILVA", "AV. OSCAR FREIRE, Nº 1001", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("GABRIEL", "AZEVEDO", "AV. OSCAR FREIRE, Nº 1002", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("LARA", "FERNANDES", "AV. OSCAR FREIRE, Nº 1003", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("DANIELLE", "MENDES", "AV. OSCAR FREIRE, Nº 1004", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("THAIS", "LINO", "AV. OSCAR FREIRE, Nº 1005", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("LUCAS", "ANSELMO", "AV. OSCAR FREIRE, Nº 1006", "JARDINS", "SP");

INSERT INTO ASSOCIADOS (NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES ("MARCUS", "RIBEIRO", "AV. OSCAR FREIRE, Nº 1007", "JARDINS", "SP");


-- INSERINDO TELEFONES
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551191111-1111');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551192222-2222');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551193333-3333');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551194444-4444');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551195555-5555');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551196666-6666');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551197777-7777');
INSERT INTO TELEFONE (TELEFONE) VALUES ('+551198888-8888');

-- INSERINDO AUTOR
INSERT INTO AUTOR (NOME, SOBRENOME) VALUES ('UPOM' , 'MALIK');
INSERT INTO AUTOR (NOME, SOBRENOME) VALUES ('ROBERT' , 'C. MARTIN');
INSERT INTO AUTOR (NOME, SOBRENOME) VALUES ('David', 'Flanagan');
INSERT INTO AUTOR (NOME, SOBRENOME) VALUES ('FULANO' , 'DE TAL');
INSERT INTO AUTOR (NOME, SOBRENOME) VALUES ('DE TAL', 'FULANO');


--  INSERINDO EDITORA
INSERT INTO EDITORA (RAZAO_SOCIAL, NOME_FANTASIA) VALUES('NOVATEC LTDA','NOVATEC');
INSERT INTO EDITORA (RAZAO_SOCIAL, NOME_FANTASIA) VALUES('ALTABOOKS LTDA','ALTABOOKS');
INSERT INTO EDITORA (RAZAO_SOCIAL, NOME_FANTASIA) VALUES('ORELLY LTDA','NOVATECORELLY');

-- INSERINDO LIVROS
INSERT INTO LIVRO (TITULO, ANO_CRIACAO, ANO_PUBLICACAO, COD_ID_AUTOR, COD_ID_EDITORA) VALUES ('TITULO 1', '2015-08-15', '2020-08-15', 1, 2);
INSERT INTO LIVRO (TITULO, ANO_CRIACAO, ANO_PUBLICACAO, COD_ID_AUTOR, COD_ID_EDITORA) VALUES ('TITULO 2', '2015-08-15', '2020-08-15', 1, 2);
INSERT INTO LIVRO (TITULO, ANO_CRIACAO, ANO_PUBLICACAO, COD_ID_AUTOR, COD_ID_EDITORA) VALUES ('TITULO 3', '2015-08-15', '2020-08-15', 1, 2);
INSERT INTO LIVRO (TITULO, ANO_CRIACAO, ANO_PUBLICACAO, COD_ID_AUTOR, COD_ID_EDITORA) VALUES ('TITULO 4', '2015-08-15', '2020-08-15', 1, 2);
INSERT INTO LIVRO (TITULO, ANO_CRIACAO, ANO_PUBLICACAO, COD_ID_AUTOR, COD_ID_EDITORA) VALUES ('TITULO 5', '2015-08-15', '2020-08-15', 1, 2);

-- INSERINDO EXEMPLARES
INSERT INTO EXEMPLAR (SINISTRO, COD_ID_LIVRO) VALUES (1, 1);
INSERT INTO EXEMPLAR (SINISTRO, COD_ID_LIVRO) VALUES (0, 2);
INSERT INTO EXEMPLAR (SINISTRO, COD_ID_LIVRO) VALUES (1, 3);
INSERT INTO EXEMPLAR (SINISTRO, COD_ID_LIVRO) VALUES (0, 4);
INSERT INTO EXEMPLAR (SINISTRO, COD_ID_LIVRO) VALUES (0, 5);

-- INSERINDO EMPRESTIMOS_EXEMPLARES
INSERT INTO EMPRESTIMO_EXEMPLAR (COD_ID_EMPRESTIMO, COD_ID_EXEMPLAR) VALUES (1, 1);
INSERT INTO EMPRESTIMO_EXEMPLAR (COD_ID_EMPRESTIMO, COD_ID_EXEMPLAR) VALUES (2, 2);
INSERT INTO EMPRESTIMO_EXEMPLAR (COD_ID_EMPRESTIMO, COD_ID_EXEMPLAR) VALUES (3, 3);
INSERT INTO EMPRESTIMO_EXEMPLAR (COD_ID_EMPRESTIMO, COD_ID_EXEMPLAR) VALUES (4, 4);
INSERT INTO EMPRESTIMO_EXEMPLAR (COD_ID_EMPRESTIMO, COD_ID_EXEMPLAR) VALUES (5, 5);

-- INSERINDO EMPRESTIMOS 
INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO, ID_COD_ASSOCIADOS) VALUES ('2020-01-15','2020-02-15', '2020-02-14', 1);
INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO, ID_COD_ASSOCIADOS) VALUES ('2020-01-15','2020-02-15', '2020-02-14', 2);
INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO, ID_COD_ASSOCIADOS) VALUES ('2020-01-15','2020-02-15', '2020-02-14', 3);
INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO, ID_COD_ASSOCIADOS) VALUES ('2020-01-15','2020-02-15', '2020-02-14', 4);
INSERT INTO EMPRESTIMO (DATA_EMPRESTIMO, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO, ID_COD_ASSOCIADOS) VALUES ('2020-01-15','2020-02-15', '2020-02-14', 5);


-- DELETANDO ASSOCIADO
DELETE FROM ASSOCIADOS WHERE ID_ASSOCIADOS = 8;

-- DELETANDO LIVRO
DELETE FROM LIVRO WHERE ID_LIVRO = 5;

-- UPDATE EM UM ENDEREÇO
UPDATE ASSOCIADOS
SET ENDERECO = 'ALTERANDO ENDEREÇO, Nº 12'
WHERE ID_ASSOCIADOS = 1;





select *from LIVRO;