version: '3.8'
services:
  db:
    image: mysql:latest
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: my-secret-pw
    networks:
      - internal

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: my-secret-pw
    networks:
      - internal
      - public
    
networks:
  internal:
    internal: true
  public:
  
  # https://docs.google.com/document/d/1-lTfdr8npZAV84RhgAL4a47VFiR3Xciz/edit#
