
CREATE SCHEMA IF NOT EXISTS `BD_SPOTIFY` DEFAULT CHARACTER SET utf8 ;
USE `BD_SPOTIFY` ;

-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO` DATE NULL,
  `SEXO` VARCHAR(1) NULL,
  `EMAIL` VARCHAR(150) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`PLAYLIST` (
  `ID_PLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL,
  `TITULO` VARCHAR(45) NULL,
  `QNTD_CANCOES` INT NULL,
  `DATACRIACAO` DATETIME NULL,
  PRIMARY KEY (`ID_PLAYLIST`),
  INDEX `FK_PLAYLIST_USUARIO_idx` (`ID_USUARIO` ASC) ,
  CONSTRAINT `FK_PLAYLIST_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `BD_SPOTIFY`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`ARTISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`ARTISTA` (
  `ID_ARTISTA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `SOBRENOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ARTISTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`ALBUM` (
  `ID_ALBUM` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `ID_ARTISTA` INT NOT NULL,
  PRIMARY KEY (`ID_ALBUM`),
  INDEX `FK_ALBUM_ARTISTA_idx` (`ID_ARTISTA` ASC) ,
  CONSTRAINT `FK_ALBUM_ARTISTA`
    FOREIGN KEY (`ID_ARTISTA`)
    REFERENCES `BD_SPOTIFY`.`ARTISTA` (`ID_ARTISTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`CANCOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`CANCOES` (
  `ID_CANCOES` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `DURACAO` DOUBLE NOT NULL,
  `QTD_REPRODUCAO` INT NULL,
  `QTD_LIKES` INT NULL,
  `ID_ALBUM` INT NULL,
  PRIMARY KEY (`ID_CANCOES`),
  INDEX `FK_CANCOES_ALBUM_idx` (`ID_ALBUM` ASC) ,
  CONSTRAINT `FK_CANCOES_ALBUM`
    FOREIGN KEY (`ID_ALBUM`)
    REFERENCES `BD_SPOTIFY`.`ALBUM` (`ID_ALBUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`PLAYLIST_CANCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`PLAYLIST_CANCAO` (
  `ID_PLAYLIST_CANCAO` INT NOT NULL AUTO_INCREMENT,
  `ID_PLAYLIST` INT NOT NULL,
  `ID_CANCAO` INT NOT NULL,
  PRIMARY KEY (`ID_PLAYLIST_CANCAO`),
  INDEX `FK_PLAYLIST_CANCAO_CANCOES_idx` (`ID_CANCAO` ASC) ,
  CONSTRAINT `FK_PLAYLIST_CANCAO_PLAYLIST`
    FOREIGN KEY (`ID_PLAYLIST_CANCAO`)
    REFERENCES `BD_SPOTIFY`.`PLAYLIST` (`ID_PLAYLIST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAYLIST_CANCAO_CANCOES`
    FOREIGN KEY (`ID_CANCAO`)
    REFERENCES `BD_SPOTIFY`.`CANCOES` (`ID_CANCOES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`GENERO` (
  `ID_GENERO` INT NOT NULL AUTO_INCREMENT,
  `GENERO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_GENERO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SPOTIFY`.`GENERO_CANCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SPOTIFY`.`GENERO_CANCAO` (
  `ID_GENERO_CANCAO` INT NOT NULL AUTO_INCREMENT,
  `ID_GENERO` INT NOT NULL,
  `ID_CANCAO` INT NOT NULL,
  PRIMARY KEY (`ID_GENERO_CANCAO`),
  INDEX `FK_GENERO_CANCAO_CANCOES_idx` (`ID_CANCAO` ASC) ,
  INDEX `FK_GENERO_CANCAO_GENERO_idx` (`ID_GENERO` ASC) ,
  CONSTRAINT `FK_GENERO_CANCAO_CANCOES`
    FOREIGN KEY (`ID_CANCAO`)
    REFERENCES `BD_SPOTIFY`.`CANCOES` (`ID_CANCOES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GENERO_CANCAO_GENERO`
    FOREIGN KEY (`ID_GENERO`)
    REFERENCES `BD_SPOTIFY`.`GENERO` (`ID_GENERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 