-- INSERIR DADOS NA TABELA "USUÁRIOS" --
INSERT INTO USUARIO (NOME_USUARIO, DATA_NASCIMENTO, SEXO, EMAIL, SENHA)
VALUES
('GABRIEL AZEVEDO', '1991-08-28', 'M','gabriel@gmail.com', 'senhaGabriel'),
('LARA FERNANDES', '1995-02-27', 'F','lara@gmail.com', 'senhaDaLara'),
('LUCAS ANSELMO', '1993-04-3', 'M','lucas@gmail.com', 'senhaLucas');


-- INSERIR DADOS NA TABELA "ARTISTA" (BÔNUS) --
INSERT INTO ARTISTA (NOME, SOBRENOME)
VALUES ('MANO', 'BROWN'),
('MD', 'CHEFE'),
('BRUNO', 'MARS');

-- INSERIR DADOS NA TABELA "ÁLBUM" --
INSERT INTO ALBUM (ID_ALBUM, TITULO, ID_ARTISTA)
VALUES (1, 'RACIONAIS MC', 1),
(2, 'SINGLE', 2),
(3, 'SINGLE', 3);

-- INSERIR DADOS NA TABELA "CANÇÕES" --
INSERT INTO CANCOES (TITULO, DURACAO, QTD_REPRODUCAO, QTD_LIKES, ID_ALBUM)
VALUES
('VIDA LOKA PARTE 1', 651, 98432, 5600, 1),
('TIFFANY', 232, 120000, 56196, 2),
('LEAVE THE DOOR OPEN', 402, 10154, 9800, 3);

SELECT*FROM USUARIO;
SELECT*FROM ARTISTA;
SELECT*FROM CANCOES;